version: '2.1'
services:
  million-tonn-mongo:
    container_name: million-tonn-mongo
    image: mongo
    restart: always
    healthcheck:
      test: mongo --eval 'db.getCollectionNames()'
      interval: 10s
      timeout: 2s
      retries: 10
    volumes:
      - million-tonn-mongodb-vol:/data/db
    ports:
      - 127.0.0.1:27019:27017
    networks:
      - services-tier

volumes:
  million-tonn-mongodb-vol:

networks:
  services-tier:
